# This is a TOML document

title = "WeIO IDE Configuration File"

[projects]
# Only server knows where are the projects otherwise it's security breach
# client don't have permission to demand absolut paths
# all paths comming from client will always be relative to 
# this variable :
rootDirectory = "./projects"
lastOpenedProject = ""

[server]
webSocketServerPort = 8080
# todo make https server in node and bind it to this port
httpServerPort = 4200